<?php

namespace App\Models;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Category extends Model
{
    protected $fillable = [
        'title',
        'slug',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($category) {
            $category->slug = Str::slug($category->title);
        });
        static::updating(function ($category) {
            $category->slug = Str::slug($category->title);
        });

    }
}
