<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Category extends Model
{
    protected $fillable = [
        'category_id',
        'category_name',
        'created_by',
        'updated_by',
    ];  

    public function classType()
    {
        return $this->belongsTo(ClassType::class, 'class_type_id');
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function createdUser()
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    public function updatedUser()
    {
        return $this->belongsTo(User::class, 'updated_by');
    }


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($category) {
            $category->slug = Str::slug($category->category_name);
            $category->created_by = Auth::id();
        });
        static::updating(function ($category) {
            $category->slug = Str::slug($category->category_name);
            $category->updated_by = Auth::id();
        });

    }
}
