<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Auth;

class MailReplies extends Model
{
    protected $fillable = ['mail_messages_id', 'reply_email', 'reply_subject', 'reply_message', 'created_by'];

    public function createdUser(){
        return $this->belongsTo(User::class, 'created_by');
    }

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::creating(function ($reply) {
            $reply->created_by = Auth::id() ?? 1;
        });
    }
}
